runtime: python310  # La versión de Python que estás utilizando

handlers:
- url: /static
  static_dir: static  # Ruta a tus archivos estáticos (CSS, JavaScript, imágenes, etc.)

- url: /.*
  script: auto  # Esto indica que la solicitud será manejada por tu aplicación Flask

env_variables:
  FLASK_APP: "app.py"  # El nombre de tu archivo principal de Flask
